services:
  # PHP-FPM
  php-nginx-socket:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    container_name: php-nginx-socket
    restart: unless-stopped
    env_file:
      - env/.env
    volumes:
      - unix-socket:/var/run/php
      - ./public:/var/www/html
      - ./config/php/php.ini:/usr/local/etc/php/conf.d/local.ini:ro
      - ./config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      - php-nginx-socket-network
    healthcheck:
      test: [ "CMD-SHELL", "cgi-fcgi -bind -connect /var/run/php/php-fpm.sock" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Веб-сервер Nginx
  nginx-socket:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: nginx-socket
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - unix-socket:/var/run/php
      - ./public:/var/www/html
      - ./config/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - php-nginx-socket-network
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      php-nginx-socket:
        condition: service_healthy

  # База данных PostgreSQL 17
  postgres-nginx-socket:
    image: postgres:17-alpine
    container_name: postgres-nginx-socket
    restart: unless-stopped
    env_file:
      - env/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - php-nginx-socket-network
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Веб-интерфейс pgAdmin 6
  pgadmin-nginx-socket:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    env_file:
      - env/.env
    ports:
      - "8080:80"
    networks:
      - php-nginx-socket-network
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost/" ]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 10s
    depends_on:
      postgres-nginx-socket:
        condition: service_healthy

volumes:
  unix-socket:
  postgres-data:

networks:
  php-nginx-socket-network:
    driver: bridge